
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN BREAK COMMA FN IDENT IF LBRACE LPAREN NUMBER OP RBRACE RETURN RPAREN SEMICOLON WHILEprogram : functionfunction : FN LPAREN IDENT RPAREN LBRACE statements RBRACEstatements : statements statementstatements : statementstatement : IDENT ASSIGN IDENT SEMICOLONstatement : IDENT ASSIGN NUMBER SEMICOLONstatement : WHILE LPAREN condition RPAREN LBRACE statements RBRACEstatement : IF LPAREN condition RPAREN LBRACE statements RBRACEstatement : BREAK SEMICOLONstatement : RETURN IDENT SEMICOLONcondition : IDENT OP IDENT'
    
_lr_action_items = {'FN':([0,],[3,]),'$end':([1,2,16,],[0,-1,-2,]),'LPAREN':([3,11,12,],[4,18,19,]),'IDENT':([4,7,9,10,14,15,17,18,19,20,27,28,29,31,33,35,36,37,38,39,],[5,8,8,-4,21,22,-3,25,25,-9,-10,-5,-6,34,8,8,8,8,-7,-8,]),'RPAREN':([5,24,26,34,],[6,30,32,-11,]),'LBRACE':([6,30,32,],[7,33,35,]),'WHILE':([7,9,10,17,20,27,28,29,33,35,36,37,38,39,],[11,11,-4,-3,-9,-10,-5,-6,11,11,11,11,-7,-8,]),'IF':([7,9,10,17,20,27,28,29,33,35,36,37,38,39,],[12,12,-4,-3,-9,-10,-5,-6,12,12,12,12,-7,-8,]),'BREAK':([7,9,10,17,20,27,28,29,33,35,36,37,38,39,],[13,13,-4,-3,-9,-10,-5,-6,13,13,13,13,-7,-8,]),'RETURN':([7,9,10,17,20,27,28,29,33,35,36,37,38,39,],[14,14,-4,-3,-9,-10,-5,-6,14,14,14,14,-7,-8,]),'ASSIGN':([8,],[15,]),'RBRACE':([9,10,17,20,27,28,29,36,37,38,39,],[16,-4,-3,-9,-10,-5,-6,38,39,-7,-8,]),'SEMICOLON':([13,21,22,23,],[20,27,28,29,]),'NUMBER':([15,],[23,]),'OP':([25,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'function':([0,],[2,]),'statements':([7,33,35,],[9,36,37,]),'statement':([7,9,33,35,36,37,],[10,17,10,10,17,17,]),'condition':([18,19,],[24,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> function','program',1,'p_program','parser.py',10),
  ('function -> FN LPAREN IDENT RPAREN LBRACE statements RBRACE','function',7,'p_function','parser.py',18),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',22),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',26),
  ('statement -> IDENT ASSIGN IDENT SEMICOLON','statement',4,'p_statement_assign','parser.py',30),
  ('statement -> IDENT ASSIGN NUMBER SEMICOLON','statement',4,'p_statement_assign_num','parser.py',34),
  ('statement -> WHILE LPAREN condition RPAREN LBRACE statements RBRACE','statement',7,'p_statement_while','parser.py',38),
  ('statement -> IF LPAREN condition RPAREN LBRACE statements RBRACE','statement',7,'p_statement_if','parser.py',42),
  ('statement -> BREAK SEMICOLON','statement',2,'p_statement_break','parser.py',46),
  ('statement -> RETURN IDENT SEMICOLON','statement',3,'p_statement_return','parser.py',50),
  ('condition -> IDENT OP IDENT','condition',3,'p_condition','parser.py',54),
]
